#FROM radek1st/spark-jobserver:0.6.2.mesos-0.28.1.spark-1.6.1
FROM radek1st/spark-jobserver:0.6.1.mesos-0.25.0.spark-1.5.2

ADD docker.conf /app/docker.conf
ADD fairscheduler.xml /app/fairscheduler.xml
ADD models /sparkommender/models/

MAINTAINER Radek Ostrowski radek@fastdata.eu

